name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cppcheck:
    name: Run Cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Cppcheck
        run: sudo apt-get install -y cppcheck
      - name: Run Cppcheck
        run: cppcheck --enable=all --inconclusive --quiet src

  clang_tidy:
    name: Run Clang-Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang-Tidy
        run: sudo apt-get install -y clang-tidy
      - name: Run Clang-Tidy
        run: clang-tidy src/**/*.cpp --checks=*

  clang_format:
    name: Run Clang-Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Clang-Format
        run: sudo apt-get install -y clang-format
      - name: Check Clang-Format
        run: |
          clang-format -i src/**/*.cpp src/**/*.h
          git diff --exit-code

  valgrind:
    name: Run Valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Valgrind
        run: sudo apt-get install -y valgrind
      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run Valgrind
        run: valgrind --leak-check=full --track-origins=yes ./build/my_executable
